version: "3.8"

service:
  postgres:
    image: postgres:15-alpine
    container_name: ${PROJECT_ID}-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ${PROJECT_ID}-prod
  app:
    image: ghcr.io/mushee22/${PROJECT_ID}:latest
    container_name: ${PROJECT_ID}-app-prod
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - 3000
    networks:
      - ${PROJECT_ID}-prod
volumes:
  postgres_data:

networks:
  ${PROJECT_ID}-prod:
    external: true
