name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize Dockerfile 
        run: |
          sed -i 's/\r$//' Dockerfile
          echo "" >> Dockerfile

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
