name: Mirror Push to GitHub

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.name "mushee22"
          git config --global user.email "mmtmusheer@gmail.com"
      - name: Add destination repo as mirror
        env:    
          TARGET_REPO: ${{ secrets.MIRROR_REPO_URL }}
        run: |
          git remote add mirror $TARGET_REPO
          git push --mirror mirror
